### ISSUE TITLE
Web Unblocker is Not Working

### ISSUE THREAD

**Issue by JayGotHaxs** [SkyeGamesYT/Bookmarklets#2]
Wsg Skyegames I used the unblocker in the proxey folder and it say you need to verify your account to wake the repl.
![Screenshot 2023-02-03 5 53 56 PM](https://user-images.githubusercontent.com/124406794/216726227-8ea1ad99-3445-4733-bbb3-31c0003f690d.png)

**Comment by SkyeGamesYT** [comment]
Yea, This is really only for me, because it's only active when I run it, and I don't have money to pay for Replit's 24/7 Runtime option. I've tried uptimerobot, and others but nothing will work.

**Comment by JayGotHaxs** [comment]
Its alr bro just wanted to bring it to your attention if you didn't know
