### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hayhaycool** [SkyeGamesYT/Bookmarklets#4]
it wont let me open it or work at all i cant open it on the bookmark bar

**Comment by SkyeGamesYT** [comment]
Please elaborate on what you mean by "open it or work on it at all"

**Comment by SkyeGamesYT** [comment]
Also, which bookmarklet are you referring to?

**Comment by SkyeGamesYT** [comment]
I think I know. Thank you it has been fixed.
