### ISSUE TITLE
Blooket MultiTool

### ISSUE THREAD

**Issue by BuddyBukaroo** [SkyeGamesYT/Bookmarklets#5]
My Manz, They still dont work here lemme lend you the script

**Comment by SkyeGamesYT** [comment]
I now see what you mean, sorry. I will update it.

**Comment by BuddyBukaroo** [comment]
hey, I forgot to say,
if you ever wanna convert a js code into a bookmarklet use this website
it works very well
https://caiorss.github.io/bookmarklet-maker/

**Comment by BuddyBukaroo** [comment]
okay it works now TY very much

**Comment by BuddyBukaroo** [comment]
give me youre email address if you got some more trouble
